# В этом классе содержатся необходимые константы

DATA_BASE_PATH = '../data/twotwo.sqlite'
AREA = 'area'
TITLE = 'title'
LOGIN = 'login'
PASSWORD = 'password'
ITEM = 'item'
NAME = 'name'
COUNT = 'count'
BARCODE = 'barcode'
OWNER_ID = 'owner_id'
PRICE = 'price'
ID = 'id'
NOT_STATED = 'NOT_STATED'
LOGIN_NOT_FOUND_TEXT = 'Введённого вами логина не существует.'
PASSWORD_NOT_CORRECT_TEXT = 'Пароль, который вы ввели неверный.'

ENCODING_TYPE = 'utf-8'
NAME_FIELD = 'Название'
PRICE_FIELD = 'Цена'
COUNT_FIELD = 'В наличии'
BARCODE_FIELD = 'Штрих-код'
FIELDS = [NAME_FIELD, PRICE_FIELD, COUNT_FIELD, BARCODE_FIELD]
COLUMN_COUNT = len(FIELDS)
ITEM_NOT_FOUND = 'Товар не найден.'
EMPTY_LOGIN = 'Введите логин'
EMPTY_PASSWORD = 'Введите пароль'
FILE_NOT_CORRECT = 'Мы не можем открыть файл'
IMAGE_EMPTY = 'Штрих-код не найден'
EMPTY_NAME = 'Название товара не должно быть пустым.'
LOGIN_HINT = 'Имя пользователя'
PASSWORD_HINT = 'Пароль'
TITLE_HINT = 'Название'
NOT_FILE = 'Файл не выбран'